export const types = {
    NAME_INPUT: "NAME_INPUT",
    USERNAME_INPUT: "USERMANE_INPUT",
    EMAIL_INPUT: "EMAIL_INPUT",
    WEBSITE_INPUT: "WEBSITE_INPUT",
    MASSAGE: "MASSAGE",
    MASSAGE_CLOSE: "MASSAGE_CLOSE"
}